//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employeecrud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class employeedata
    {
        public int Eid { get; set; }
        [DisplayName("Employee Name")]
        [Required(ErrorMessage ="Enter Employee Name")]
        public string EmployeeName { get; set; }
        [DisplayName("Employee Address")]
        [Required(ErrorMessage = "Enter Employee Address")]
        public string EmployeeAddress { get; set; }
        [DisplayName("Employee Email")]
        [Required(ErrorMessage = "Enter Employee email address")]
        public string Employeemail { get; set; }
        [DisplayName("Employee Number")]
        [Required(ErrorMessage = "Enter Employee Phone number")]
        public string EmployeePhoneno { get; set; }
        [DisplayName("Employee Qualification")]
        [Required(ErrorMessage = "Enter Employee Qualification")]
        public string EmployeeQualification { get; set; }
    }
}
